# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: content-sources-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: content-sources
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: ContentSources
      deploymentRepo: https://github.com/content-services/content-sources-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/content-sources
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: /apps/content-sources/fed-mods.json
        modules:
          - id: insights-content-sources
            module: ./RootApp
            routes:
              - pathname: /insights/content
      bundleSegments:
        - segmentId: content
          bundleId: insights
          position: 600
          navItems:
            - id: content
              title: Content
              expandable: true
              routes:
                - segmentRef:
                    frontendName: patch
                    segmentId: patch-advisories-packages
                - id: repositories
                  title: Repositories
                  href: /insights/content/repositories
                - id: templates
                  title: Templates
                  href: /insights/content/templates
                - segmentRef:
                    frontendName: patch
                    segmentId: patch-systems
      serviceTiles:
        - section: observe
          group: rhel
          id: repositories
          href: /insights/content/repositories
          title: Repositories
          description: 'Link your external repositories to build images.' # TODO: this doesn't mention templates currently and that's the main use case for repos, so maybe it should
          icon: InsightsIcon
        - section: '' # TODO: Where?
          group: '' # ^
          id: templates
          href: /insights/content/templates
          title: Templates
          description: '' # TODO: What?
          icon: InsightsIcon
      searchEntries:
        - id: repositories
          title: Repositories
          href: /insights/content/repositories
          description: 'Link your external repositories to build images.' # TODO : ditto
          alt_title:
            - 'content'
            - 'custom content'
            - 'my content'
            - 'my repos'
            - 'repos'
            - 'repo'
            - 'repositories'
            - 'repository'
            - 'repository sets'
            - 'Red Hat repositories'
            - 'introspect'
            - 'snapshot'
            - 'upload'
            - 'epel'
            - 'community'
            - 'dnf'
            - 'yum'
            - 'rpms'
            - 'rpm'
            - 'insights'
        - id: templates
          title: Templates
          href: /insights/content/templates
          description: '' # TODO: What?
          alt_title:
            - '' # TODO: What?
            - ''

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-content-sources/content-sources-frontend
